datasaet: cora,  model: sage.
time of construct data:0.27229809761047363
epoch: 0, val_loss: 1.8402661681175232
Traceback (most recent call last):
  File "main_shuffle.py", line 67, in <module>
    result = train_model(features,labels,num_sample,hidden,cuda,gcn,beta,lr,train_idx,val_idx,test_idx,full_adjs_shuffled,batch_size,epochs,dataset,patience,r,interval)
  File "/home/zhihao/Document/gnn_fd/graphSage/split/multihead/NC-GNN/train1.py", line 26, in train_model
    result = train(model,optimizer,train_idx,val_idx,test_idx,full_adjs_dict,features,labels,batch_size,lr,len(np.unique(labels)),epochs,dataset,cuda,gcn,patience)
  File "/home/zhihao/Document/gnn_fd/graphSage/split/multihead/NC-GNN/train1.py", line 177, in train
    torch.save(model.state_dict(),temp_path+'{}.pkl'.format(epoch))
  File "/home/zhihao/.conda/envs/torch-gpu/lib/python3.8/site-packages/torch/serialization.py", line 376, in save
    with _open_file_like(f, 'wb') as opened_file:
  File "/home/zhihao/.conda/envs/torch-gpu/lib/python3.8/site-packages/torch/serialization.py", line 230, in _open_file_like
    return _open_file(name_or_buffer, mode)
  File "/home/zhihao/.conda/envs/torch-gpu/lib/python3.8/site-packages/torch/serialization.py", line 211, in __init__
    super(_open_file, self).__init__(open(name, mode))
FileNotFoundError: [Errno 2] No such file or directory: '~/temp/intermediate/cora/0.pkl'
